common: &common
  adapter: postgresql
  username: educentives_user
  password: 

development:
  <<: *common
  database: educentives_development
  host: localhost

test: &test
  <<: *common
  database: educentives_test
  host: localhost

production:
  <<: *common
  database: educentives_production


cucumber:
  <<: *test
  host: localhost
