common: &common
  adapter: postgresql
  username: educentives_user
  password: 

development:
  <<: *common
  database: educentives_development

test: &test
  <<: *common
  database: educentives_test

production:
  <<: *common
  database: educentives_production


cucumber:
  <<: *test
